feat(databases): add maintenance
Scalingo/developers-documentation pull request #330
Opened 2023-07-10 13:24 UTC by SCedricThomas

fix #329

2023-07-13 14:05 UTC, yohann-bacha reviewed
well if the api has indeed a "maintenance" without plural, but containing multiple maintenances, this is not coherent. but well if it is already implemented like that everywhere, well we'll gonna stay like this

2023-07-13 14:35 UTC, SCedricThomas commented on _database_api/maintenance.md
> +  "maintenance": [
maintenance common plural form has no 's'

2023-07-13 14:39 UTC, SCedricThomas commented on _database_api/maintenance.md
> +  "maintenance": [
https://www.wordhippo.com/what-is/the-plural-of/maintenance.html

2023-07-17 09:27 UTC, SCedricThomas commented
![Screenshot from 2023-07-17 11-27-11](https://github.com/Scalingo/developers-documentation/assets/112880007/365c9b26-20a0-4024-b2f4-a02099130954)
![Screenshot from 2023-07-17 11-27-17](https://github.com/Scalingo/developers-documentation/assets/112880007/9b614155-30b7-445e-97c0-714a20478a1a)

2023-07-17 09:50 UTC, curzolapierre requested changes

2023-07-17 09:50 UTC, curzolapierre commented on _database_api/maintenance.md
> +`GET https://$DB_API_URL/api/databases/[:db_id]/maintenances?page=[:page_number]&per_page=[:per_page_number]`
We don't usually display the pagination parameter. Instead, you can do the same as for the logs-archive, for example. By specifying that this request supports the pagination system.

2023-07-17 09:50 UTC, curzolapierre commented on _database_api/maintenance.md
> +  -X GET https://$DB_API_URL/api/databases/my-db-123/maintenances/my-maintenance-123
```suggestion
  -X GET https://$DB_API_URL/api/databases/my-db-123/maintenance/my-maintenance-123
```

2023-07-17 13:55 UTC, curzolapierre approved these changes

2023-07-17 14:06 UTC, curzolapierre approved these changes
Thanks for the update of pagination object !

2023-07-18 13:08 UTC, yohann-bacha approved these changes

2023-07-19 14:27 UTC, merged