docs(json-schema): fix link to container sizes
Scalingo/developers-documentation pull request #388
Opened 2024-02-05 21:37 UTC by revolunet

fix broken link

2024-02-06 09:40 UTC, EtienneM requested changes
Thanks a lot

2024-02-06 09:40 UTC, EtienneM commented on _scalingo_json_schema/index.md
> +| size     | string  | Container size `name` ([get the list of sizes](https://doc.scalingo.com/platform/internals/container-sizes)) |
We actually want to target the documentation page explaining the API endpoint to list container sizes.

```suggestion
| size     | string  | Container size `name` ([get the list of sizes](/container_sizes#list-the-container-sizes-available)) |
```

2024-02-06 09:41 UTC, EtienneM approved these changes

2024-02-06 09:41 UTC, merged

2024-02-06 09:49 UTC, revolunet commented
Would you be interested in a PR with the working JSON-schema ?

With it you can autodetect `scalingo.json` files and provide linting and documentation right from the editor.

<img width="682" alt="Capture d’écran 2024-02-06 à 10 46 09" src="https://github.com/Scalingo/developers-documentation/assets/124937/c457470f-91ff-4e8b-b6c3-d3499f8499b5">

---

<img width="524" alt="Capture d’écran 2024-02-06 à 10 46 16" src="https://github.com/Scalingo/developers-documentation/assets/124937/9435989c-87b0-4c65-8c15-26257bbab47d">

---

<img width="288" alt="Capture d’écran 2024-02-06 à 10 49 02" src="https://github.com/Scalingo/developers-documentation/assets/124937/072f40f5-9b84-48d5-a64a-54ba219065c4">

2024-02-08 15:41 UTC, leo-scalingo commented
Hi @revolunet 

Indeed it's something which would be really useful. Could you tell us a bit more about how you've generated/used this schema?

Thanks a lot

2024-02-08 16:51 UTC, revolunet commented
More here : https://github.com/Scalingo/developers-documentation/pull/390