feat: add scalingo.schema.json
Scalingo/developers-documentation pull request #390
Opened 2024-02-08 16:48 UTC by revolunet

A json-schema proposal for the `scalingo.json` file. This allows linting and documentation from your editor.

Its been created manually from the docs and tested against various `scalingo.json` examples.

Once this file is published, we can add it to [SchemaStore](https://github.com/SchemaStore/schemastore) so every IDE can associate `scalingo.json` to the published schema. 

Meanwhile, you can see it in action by adding `"$schema":https://raw.githubusercontent.com/Scalingo/developers-documentation/ba2c542c3a8c77145445a942c1ffc14790ce8799/scalingo.schema.json` to your `scalingo.json`. If you use VScode and the [Red Hat YAML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) then you you should see documentation appear instantly.

Note: The `addons.plan` key provide some examples but no restriction on what you can set here. (would be cool to have an exhaustive list if possible)

Some examples: 

<img width="682" alt="Capture d’écran 2024-02-06 à 10 46 09" src="https://github.com/Scalingo/developers-documentation/assets/124937/10074476-dcba-425b-8f92-6ebe2364a8a4">
<img width="288" alt="Capture d’écran 2024-02-06 à 10 49 02" src="https://github.com/Scalingo/developers-documentation/assets/124937/56604529-e163-4c6a-96d7-dfc524b9454b">
<img width="352" alt="Capture d’écran 2024-02-06 à 10 48 07" src="https://github.com/Scalingo/developers-documentation/assets/124937/63e81dff-e30c-4111-8153-806aee5fe2af">
<img width="288" alt="Capture d’écran 2024-02-06 à 10 46 52" src="https://github.com/Scalingo/developers-documentation/assets/124937/eef4c1de-63dc-4784-ac14-0cd5691aa743">
<img width="524" alt="Capture d’écran 2024-02-06 à 10 46 16" src="https://github.com/Scalingo/developers-documentation/assets/124937/c6d91df1-bb44-41f2-870b-6a300ab2e872">

2024-06-17 08:20 UTC, ksol commented
👋🏼  Hello @revolunet, sorry for not getting back to you on this topic sooner, and thanks for the submission! I'll add this on our plate of things to review, but it's indeed something that we'd benefit from

2025-01-22 15:24 UTC, aurelien-reeves-scalingo requested changes
Hi @revolunet 

Sorry for the huge delay!

Thanks for your contribution!

Do you think it would be possible to add a link to the schema somewhere in `./_scalingo_json_schema/index.md`?

2025-01-22 16:02 UTC, aurelien-reeves-scalingo approved these changes
Thanks a lot for your contribution!

Once again, sorry for the delay of the review

2025-01-22 16:03 UTC, merged

2025-01-22 16:09 UTC, revolunet commented
no worries :)

will you add an entry to https://github.com/SchemaStore/schemastore to cover scalingo.json files ?